CREATE TABLE IF NOT EXISTS `users` (
    `id`         BIGINT        NOT NULL AUTO_INCREMENT,
    `name`       VARCHAR(64)   NOT NULL DEFAULT '',
    `email`      VARCHAR(128)  NOT NULL DEFAULT '',
    `password`   VARCHAR(256)  NOT NULL DEFAULT '',
    `created_at` DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `idx_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
